/*
 * Copyright (c) 2022 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-4-Clause
 */

/*
 Reference: 3GPP 24.301 V14100 Annex A
*/

const causeValues = {
    // A.1 Causes related to UE identification
    2: {
        short: 'IMSI unknown in HSS',
        long: 'This EMM cause is sent to the UE if the UE is not known (registered) in the HSS or if the UE has packet only subscription. This EMM cause does not affect operation of the EPS service, although is may be used by an EMM procedure.',
    },
    3: {
        short: 'Illegal UE',
        long: 'This EMM cause is sent to the UE when the network refuses service to the UE either because an identity of the UE is not acceptable to the network or because the UE does not pass the authentication check, i.e. the RES received from the UE is different from that generated by the network.',
    },
    6: {
        short: 'Illegal ME',
        long: 'This EMM cause is sent to the UE if the ME used is not acceptable to the network, e.g. blacklisted.',
    },
    9: {
        short: 'UE identity cannot be derived by the netowork',
        long: `This EMM cause is sent to the UE when the network cannot derive the UE's identity from the GUTI/S-TMSI/P-TMSI and RAI e.g. no matching identity/context in the network or failure to validate the UE's identity due t integrity check failure of the received message.`,
    },
    10: {
        short: 'Implicitly detached',
        long: 'This EMM cause is sent to the UE either if the network has implicitly detached the UE, e.g. after the implicit detach timer has expired, or if the EMM context data related to the subscription does not exist in the MME e.g. because of a MME restart, or because of a periodic tracking area update request routed to a new MME.',
    },

    // A.2 Cause related to subscription options
    5: {
        short: 'IMEI not accepted',
        long: 'This cause is sent to the UE if the network does not accept an attach procedure for emergency bearer services using an IMEI.',
    },
    7: {
        short: 'EPS service not allowed',
        long: 'This EMM cause is sent to the UE when it is not allowed to operate EPS services.',
    },
    8: {
        short: 'EPS service and non-EPS service not allowed',
        long: 'This EMM cause is sent to the UE when it is not allowed to operate either EPS or non-EPS services.',
    },
    11: {
        short: 'PLMN not allowed',
        long: 'This EMM cause is sent to the UE if it requests service, or if the network initiates a detach request, in a PLMN where the UE, by subscription or due to operator determined barring, is not allowed to operate.',
    },
    12: {
        short: 'Tracking area not allowed',
        long: 'This EMM cause is sent to the UE if it requests service, or if the network initiates a detach request, in a tracking area where the HPLMN determines that the UE, by subscription, is not allowed to operate.',
        notes: [
            'If EMM cause #12 is sent to a roaming subscriber the subscriber is denied service even if other PLMNs are available on which registration was possible.',
        ],
    },
    13: {
        short: 'Roaming not allowed in this tracking area',
        long: 'This EMM cause is sent to an UE which requests service, or if the network initiates a detach request, in a tracking area of a PLMN which by subscription offers roaming to that UE but not in that tracking area.',
    },
    14: {
        short: 'EPS service not allowed in this PLMN',
        long: 'This EMM cause is sent to the UE which requests service, or if the network initiates a detach request, in a PLMN which does not offer roaming for EPS services to that UE.',
        notes: [
            'Since only one list of forbidden PLMNs for packet services is maintained in the UE, then the "forbidden PLMNs for GPRS service" is the maintained list and the forbidden PLMNs for EPS service is equivalent to it.',
        ],
    },
    15: {
        short: 'No suitable cells in tracking area',
        long: 'This EMM cause is sent to the UE if it requests service, or if the network initiates a detach request, in a tracking area where the UE, by subscription, is not allowed to operate, but when it should find another allowed tracking area or location area in the same PLMN or an equivalent PLMN.',
        notes: [
            'Cause #15 and cause #12 differ in the fact that cause #12 does not trigger the UE to search for another allowed tracking area on the same PLMN.',
        ],
    },
    25: {
        short: `Not authorized for this CSG', long: 'This EMM cause is sent to the UE if it requests access, or if the network initiates a detach request, in a CSG cell with CSG ID where the UE either has no subscription to operate or the UE's subscription has expired and it should find another cell in the same PLMN or an equivalent PLMN.`,
    },
    35: {
        short: 'Requested service option not authorized in this PLMN',
        long: 'This EMM cause is sent to the UE if it requests in a PLMN a service option for which it is not authorized, e.g. if it attempts to attach for relay node operation in a PLMN with a USIM which does not belong to a relay node-specific subscription',
    },
    40: {
        short: 'No EPS bearer context activated',
        long: 'This EMM cause is sent to the UE, if during a tracking area updating procedure or a service request, the MME detects that there is no active EPS bearer context in the network.',
    },

    // A.3 Causes related to PLMN specific network failures and congestion/authentication failures
    16: {
        short: 'MCS temporarily not reachable',
        long: 'This EMM cause is sent to the UE if it requests a combined EPS attach or tracking area updating in a PLMN where the MSC is temporarily not reachable via the EPS part of the network.',
    },
    17: {
        short: 'Network failure',
        long: 'This EMM cause is sent to the UE if the MME cannot service an UE generated request because of PLMN failures.',
    },
    18: {
        short: 'CS domain not available',
        long: 'This EMM cause is sent to the UE if the MME cannot service an UE generated request because CS domain is not available and SMS in MME is not supported.',
    },
    19: {
        short: 'ESM failure',
        long: 'This EMM cause is sent to the UE when there is a failure in the ESM message contained in the EMM message.',
    },
    20: {
        short: 'MAC failure',
        long: 'This EMM cause is sent to the network if the USIM detects that the MAC in the AUTHENTICATION REQUEST message is not fresh (see 3GPP TS 33.401 [19])',
    },
    21: {
        short: 'Synch failure',
        long: 'This EMM cause is sent to the network if the USIM detects that the SQN in the AUTHENTICATION REQUEST message is out of range (see 3GPP TS 33.401 [19]).',
    },
    22: {
        short: 'Congestion',
        long: 'This EMM cause is sent to the UE because of congestion in the network (e.g. no channel, facility busy/congested etc.).',
    },
    23: {
        short: 'UE security capabilities mismatch',
        long: 'This EMM cause is sent to the network if the UE detects that the UE security capability does not match the one sent back by the network.',
    },
    24: {
        short: 'Security mode rejected, unspecified',
        long: 'This EMM cause is sent to the network if the security mode command is rejected by the UE if the UE detects that the nonceUE does not match the one sent back by the network or for unspecified reasons.',
    },
    26: {
        short: 'Non-EPS authentication unacceptable',
        long: 'This EMM cause is sent to the network in S1 mode if the "separation bit" in the AMF field of AUTN is set to 0 in the AUTHENTICATION REQUEST message (see 3GPP TS 33.401 [19]).',
    },
    39: {
        short: 'CS service temporarily not available',
        long: 'This EMM cause is sent to the UE when the CS fallback or 1xCS fallback request cannot be served temporarily due to O&M reasons or a mobile terminating CS fallback call is aborted by the network during call establishment (see 3GPP TS 29.118 [16A]).',
    },
    42: {
        short: 'Severe network failure',
        long: 'This EMM cause is sent to the UE when the network has determined that the requested procedure cannot be completed successfully due to network failure. The failure is not expected to be temporary and repeated request is not likely to succeed in near future.',
    },

    // A.4 Causes related to nature of request
    // No subclause entries in this verison.

    // A.5 Causes related to invalid messages
    95: {
        short: 'Semantically incorrect message.',
        long: 'See 3GPP TS 24.008 [13], annex H, subclause H.5.5.',
    },
    96: {
        short: 'Invalid mandatory information.',
        long: 'See 3GPP TS 24.008 [13], annex H, subclause H.6.1.',
    },
    97: {
        short: 'Message type non-existent or not implemented.',
        long: 'See 3GPP TS 24.008 [13], annex H, subclause H.6.2.',
    },
    98: {
        short: 'Message type not compatible with protocol state.',
        long: 'See 3GPP TS 24.008 [13], annex H, subclause H.6.3.',
    },
    99: {
        short: 'Information element non-existent or not implemented.',
        long: 'See 3GPP TS 24.008 [13], annex H, subclause H.6.4.',
    },
    100: {
        short: 'Conditional IE error.',
        long: 'See 3GPP TS 24.008 [13], annex H, subclause H.6.5.',
    },
    101: {
        short: 'Message not compatible with protocol state.',
        long: 'See 3GPP TS 24.008 [13], annex H, subclause H.6.6.',
    },
    111: {
        short: 'Protocol error, unspecified.',
        long: 'See 3GPP TS 24.008 [13], annex H, subclause H.6.8.',
    },
};

export default causeValues;
